### ISSUE TITLE
Feature: Do the work for me :)

### ISSUE THREAD

**Issue by janlimpens** [liyanage/album-artwork-assistant#14]
I have quite a large library of music without album art. For me it would be ideal, if the assistant could 
1) recurse through my itunes library to find albums without album images
2) search in the db including the artist name to have more reliable hits
3) apply the first hit to the album and add it to the list

I can then review the list, fine tune it where necessary and have to do 90% less work. I know I am lazy, but it is all about lazyness, in't it? If I am not mistaken, all is already in place for this - except for finding the needy albums - I guess, nothing too complicated...

Thanks for the effort you put into this!

--jan

**Comment by liyanage** [comment]
Nice ideas, I probably won't have time to work on them anytime soon though.

Regarding 2.), note that you can switch it to do that with the little magnifying glass popup menu in the search field. I plan to make that setting sticky across relaunches sometime.
