### ISSUE TITLE
While looking at "images" there is an error popup stating "The requested url was not found on this server"

### ISSUE THREAD

**Issue by NassFas** [liyanage/album-artwork-assistant#16]
Guessing this is a safari issue
On OS X 10.8
Going to "Web" works though
![Untitled](https://user-images.githubusercontent.com/98911546/152235446-ee75cb4c-f700-4096-8501-8b0e0e158f81.png)
.

**Comment by liyanage** [comment]
Hi there, unfortunately this project is no longer maintained, the code is more than 10 years old. I'm very surprised if the app still even runs...
